# Configuration file for i18n-check validation.
# See https://github.com/activist-org/i18n-check for details.

src-dir: tests
i18n-dir: tests/test_frontend/test_i18n
i18n-src: tests/test_frontend/test_i18n/test-i18n-src.json
i18n-map: tests/test_frontend/test-i18n-map.ts

checks:
  - key-identifiers: true
  - unused-keys: true
  - non-source-keys: true
  - repeat-values: true
  - map-object: true

file-types-to-check: [.ts]
directories-to-skip: []
files-to-skip: []
warn-on-nested-i18n-src: true
spdx-license-identifier: GPL-3.0-or-later
