# Configuration file for i18n-check validation.
# See https://github.com/activist-org/i18n-check for details.

src-dir: tests
i18n-dir: tests/test_frontend/test_i18n
i18n-src: tests/test_frontend/test_i18n/test_i18n_src.json

checks:
  all:
    active: true
    skip: [frontend/node_modules]
  invalid-keys:
    active: true
    skip: []
  key-identifiers:
    active: true
    skip: []
  non-source-keys:
    active: true
    skip: []
  repeat-values:
    active: true
    skip: []
  unused-keys:
    active: true
    skip: []

file-types-to-check: [.ts,.js]
files-to-skip: []
warn-on-nested-i18n-src: true
