# Configuration file for i18n-check validation.
# See https://github.com/activist-org/i18n-check for details.

src-dir: tests
i18n-dir: tests/test_frontends/all_checks_fail/test_i18n
i18n-src: tests/test_frontends/all_checks_fail/test_i18n/test_i18n_src.json

checks:
  global:
    active: true
    skip: []

file-types-to-check: [.ts]
files-to-skip: []
warn-on-nested-keys: true
